---
# Intentionally no rules, as these are maintained by the HNCConfiguration reconciler.
# At present controller-gen is unable to generate a webhook without rules from kubebuilder markers.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-objects
  failurePolicy: Fail
  name: objects.hnc.x-k8s.io
  sideEffects: None
  timeoutSeconds: 2
  # We only apply this object validator on non-excluded namespaces, which have
  # the "included-namespace" label set by the HC reconciler, so that when HNC
  # (webhook service specifically) is down, operations in the excluded
  # namespaces won't be affected. Validators on HNC CRs are not filtered because
  # they are supposed to prevent abuse of HNC CRs in excluded namespaces.
  # Namespace validator is not filtered to prevent abuse of the included-namespace
  # label on excluded namespaces. Unfortunately, this means that when HNC is
  # down, we will block updates on all namespaces, even "excluded" ones, but
  # anyone who can update namespaces like `kube-system` should likely be able to
  # delete the VWHConfiguration to make the updates.
  namespaceSelector:
    matchLabels:
      hnc.x-k8s.io/included-namespace: "true"
